### ISSUE TITLE
(Python -V 3.10.13) Error : expected an indented block after 'except' statement on line 240

### ISSUE THREAD

**Issue by m4a1carbin4** [fraunhoferhhi/nncodec#2]
``` bash
Traceback (most recent call last):
  File "/my_data/nncodec/test.py", line 1, in <module>
    import nnc
  File "/my_data/nncodec/nnc/__init__.py", line 41, in <module>
    from .compression import compress, decompress, compress_model, decompress_model, guess_block_id_and_param_type
  File "/my_data/nncodec/nnc/compression.py", line 54, in <module>
    from framework import tensorflow_model
  File "/my_data/nncodec/framework/__init__.py", line 46, in <module>
    from . import tensorflow_model
  File "/my_data/nncodec/framework/tensorflow_model/__init__.py", line 242
    model_file = h5py.File(model_path, 'r')
    ^
IndentationError: expected an indented block after 'except' statement on line 240
```
an error during the usage test in Python 3.10.13 version. There was no problem with the behavior after simple correction.
(ADD TAB)

**Comment by phaase-hhi** [comment]
Fixed! Thanks for bringing this to our attention.
